name: Publish Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "🚀 Deployment OK - Powered by Melissa"
